language: node_js
sudo: false
node_js:
  - "node"

branches:
  only:
  - staging

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli
script: gulp files_changed